### PR TITLE
First duck change

### PR DESCRIPTION
**Pull request by dhanrajtammina**
@suvarna-tammina  There is change for Ducks
#26

### CODE REVIEW

**Review by suvarna-tammina — APPROVED** [review]
@dhanrajtammina   Looks Good.

**Comment by dhanrajtammina** [comment]
First merge request......

**Review by suvarna-tammina — CHANGES_REQUESTED** [review]
@dhanrajtammina  Change the code by seeing the #23 example.

**Review by suvarna-tammina — APPROVED** [review]
@dhanrajtammina  Everything Looks Good.

**Pull request merged**
